import fs from 'node:fs';
import { exec } from 'node:child_process';
import { promisify } from 'node:util';
import path from 'node:path';
import {
	componentsJsonSchema,
	registryItemSchema,
	registrySchema,
	type Registry
} from 'lily-svelte/schema';
import { toJSONSchema } from 'zod';
import { buildRegistry } from './registry.js';
import { buildStyleSources, generatedRoot } from './design-styles.js';
import { STYLE_NAMES, type StyleName } from 'lily-svelte/styles';

const execAsync = promisify(exec);

const REGISTRY_PATH = path.resolve('static', 'registry');

function writeFileWithDirs(filePath: string, data: string): void {
	if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf8') === data) return;
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, data, 'utf-8');
}

function log(message: string) {
	console.log(`[registry]: ${message}`);
}

function validateRegistry(registry: Registry['items']) {
	const selfReferenced = registry.filter(
		(item) => item.registryDependencies?.includes(item.name) ?? false
	);
	const selfReferenceError = selfReferenced
		.map((item) => `Registry item '${item.name}' depends on itself`)
		.join('\n');
	if (selfReferenceError) {
		throw new Error(selfReferenceError);
	}

	const names = new Set(registry.map((item) => item.name));
	const unresolvedError = registry
		.flatMap((item) =>
			(item.registryDependencies ?? [])
				.filter((dep) => !dep.startsWith('http') && !names.has(dep))
				.map(
					(dep) => `Registry item '${item.name}' depends on '${dep}', which is not in the registry`
				)
		)
		.join('\n');
	if (unresolvedError) {
		throw new Error(unresolvedError);
	}
}

async function buildStyle(style: StyleName): Promise<void> {
	log('📦 Starting...');

	log('🔍 Crawling registry (ui, lib, hooks, blocks, examples)...');
	const items = await buildRegistry(path.join(generatedRoot, style));
	log(`✨ Found ${items.length} registry items`);

	log('✅ Validating registry...');
	validateRegistry(items);

	// ----------------------------------------------------------------------------
	// Assemble registry.json (consumed by the lily CLI, then deleted).
	// ----------------------------------------------------------------------------
	const result = registrySchema.parse(
		{
			$schema: './static/schema/registry.json',
			name: 'lily',
			homepage: 'https://lily-svelte.levish.workers.dev',
			aliases: {
				lib: `$lib/registry-styles/${style}/lib`,
				ui: `$lib/registry-styles/${style}/ui`,
				components: './components',
				hooks: `$lib/registry-styles/${style}/hooks`,
				utils: '$lib/utils'
			},
			items
		} as Registry,
		// maintains the schema-defined property order
		{ jitless: true }
	);

	const registryJsonPath = path.resolve(`registry-${style}.json`);
	fs.writeFileSync(registryJsonPath, JSON.stringify(result, null, '\t'), 'utf8');

	// ----------------------------------------------------------------------------
	// Hand off to the lily CLI to emit per-item JSON + index.json.
	// ----------------------------------------------------------------------------
	log('🛠️  Building per-item registry JSON via lily CLI...');
	const cwd = process.cwd();
	const cliPath = path.resolve(cwd, '..', 'packages', 'cli', 'dist', 'index.mjs');
	try {
		await execAsync(
			`node "${cliPath}" registry build "${registryJsonPath}" --output "${style === 'diamond' ? REGISTRY_PATH : path.join(REGISTRY_PATH, 'styles', style)}" -c "${cwd}"`,
			{ cwd }
		);
	} finally {
		if (fs.existsSync(registryJsonPath)) fs.rmSync(registryJsonPath);
	}

	const outputRoot =
		style === 'diamond' ? REGISTRY_PATH : path.join(REGISTRY_PATH, 'styles', style);
	const expected = new Set(['index.json', ...items.map((item) => `${item.name}.json`)]);
	for (const file of fs.readdirSync(outputRoot, { withFileTypes: true })) {
		if (!file.isFile() || !file.name.endsWith('.json') || expected.has(file.name)) continue;
		const output = path.resolve(outputRoot, file.name);
		if (path.dirname(output) !== outputRoot) throw new Error('Invalid registry output path');
		fs.unlinkSync(output);
	}

	// ----------------------------------------------------------------------------
	// Build __registry__/index.js — maps each example to its source file(s).
	// Consumed by mdsx.config.js (rehypeComponentExample) and the
	// `componentPreviews` preprocessor to render <ComponentPreview> blocks.
	// ----------------------------------------------------------------------------
	if (style !== 'diamond') return;
	log('🧩 Building __registry__/index.js...');
	let index = `// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const Index = {`;
	for (const item of items) {
		if (item.type !== 'registry:example') continue;
		const resolveFiles = (item.files ?? []).map((file) =>
			file.path
				.replaceAll(path.sep, '/')
				.replace('src/', '../')
				.replace('registry-styles/diamond/', 'registry/')
		);
		index += `
	"${item.name}": {
		files: [${resolveFiles.map((f) => `"${f}"`).join(', ')}],
	},`;
	}
	index += `
};
`;
	writeFileWithDirs(path.resolve('src', '__registry__', 'index.js'), index);

	// ----------------------------------------------------------------------------
	// Build __registry__/blocks.js — the list of block names. Drives the
	// prerender entries for /view/[view], /api/block/[block] and /blocks.
	// ----------------------------------------------------------------------------
	log('🧱 Building __registry__/blocks.js...');
	const blockNames = items.filter((item) => item.type === 'registry:block').map((i) => i.name);
	writeFileWithDirs(
		path.resolve('src', '__registry__', 'blocks.js'),
		`// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const blocks = ${JSON.stringify(blockNames, null, '\t')};
`
	);

	// ----------------------------------------------------------------------------
	// Emit JSON schemas (for editor autocomplete / validation).
	// ----------------------------------------------------------------------------
	log('📋 Writing schema files...');
	writeFileWithDirs(
		path.resolve('static', 'schema.json'),
		JSON.stringify(toJSONSchema(componentsJsonSchema), null, '\t')
	);
	writeFileWithDirs(
		path.resolve('static', 'schema', 'registry.json'),
		JSON.stringify(toJSONSchema(registrySchema), null, '\t')
	);
	writeFileWithDirs(
		path.resolve('static', 'schema', 'registry-item.json'),
		JSON.stringify(toJSONSchema(registryItemSchema), null, '\t')
	);

	log('🎉 Done!');
}

export async function build() {
	buildStyleSources();
	for (const style of STYLE_NAMES) await buildStyle(style);
}

if (process.argv.includes('build-registry')) {
	build();
}
